apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  type: NodePort  # Expose the service via a NodePort
  selector:
    app: mywebsite
  ports:
    - protocol: TCP
      port: 80  # Port your app listens on inside the container
      targetPort: 80  # Port on the container
      nodePort: 30007  # External port (accessible on your Minikube or cluster node)

